### ISSUE TITLE
{Initial Feature: Calendar}【Sub-Issue】 Add Event button

### ISSUE THREAD

**Issue by Ojani** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#147]
description to be added by assignee

**Comment by GabyMarr** [comment]
Description:
This issue is a continuation of the work discussed in Issue https://github.com/uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management/issues/146, and involves implementing a button "add event" on the event section. The button should be visible at all times while in calendar screen.

Acceptance Criteria:
The button is styled appropriately and integrates well with the website's overall design.
The button appears at all times during the viewing of the calendar page.
The functionality is tested across multiple devices and browsers to ensure responsiveness and performance.

Design Reference:
Figma File: [Eventero Design](https://www.figma.com/design/0N1lAA4QRe7vLjmEjBPkcG/Eventero?m=auto&t=WXZ03fz7DcJOl0ly-6)

**Comment by GabyMarr** [comment]
@Adrianortiz-PR Finished this Sub Issue
