### ISSUE TITLE
Creation of a Documentation Guide/Template

### ISSUE THREAD

**Issue by JeanSanchezFelix** [uprm-inso4101-2024-2025-s1/semester-project-campus-resource-and-event-management#47]
#### Description:
The project logbook currently lacks a standardized **Documentation Guide**. A guide is needed to ensure that all team members document their work in a consistent and structured manner, improving clarity and traceability across the project’s lifecycle. This will provide a clear reference for maintaining comprehensive records of decisions, tasks, milestones, and issues encountered throughout the project.

#### Requirements:
1. **Logbook Structure**:
   - Define the key sections for each logbook entry (e.g., **Date**, **Task Description**, **Milestones Achieved**, **Issues Encountered**, **Next Steps**).
   - Specify the format and template to be followed for each entry to ensure consistency.

2. **Documentation Standards**:
   - Set guidelines for writing clear, concise, and relevant log entries.
   - Include rules on versioning, file naming conventions, and regular updates.
   - Ensure that all entries are written in a professional tone and are easily understandable by the entire team.

3. **Purpose and Importance**:
   - Explain the importance of maintaining an up-to-date logbook, highlighting its role in tracking progress, troubleshooting issues, and reporting.

4. **Examples and Best Practices**:
   - Provide examples of well-documented log entries as a reference for team members.
   - Include tips for maintaining a useful and organized logbook, especially when dealing with complex tasks or issues.

#### Acceptance Criteria:
- A **Documentation Guide** is created for the logbook and shared with the team.
- The guide includes clear sections on log structure, documentation standards, and examples of best practices.
- All team members follow the guide when creating logbook entries, ensuring consistency and accuracy.
- The guide is easily accessible and can be updated as needed to reflect any changes in project documentation requirements.

**Comment by Ojani** [comment]
# Documentation Folder

## How to Access
Here is the [documentation folder](https://sistemaupr-my.sharepoint.com/:f:/g/personal/ojani_figueroa_upr_edu/Eqlo9P4D4UZHg4bHjCxJs90BfMWxwdf-nHmwlT38ll9_Vw?e=xrcjdD). Start by reading "Documentation Guide.docx" for an explanation of the documentation's structure.

## Plead
If all seems well in the documentation, I'd appreciate for the issue to be closed having only myself as the contributor since I was the only one who made the documentation guide. I don't intend on closing issues with multiple participants on my own, but the verification of my work by the managers is part of their role, so there's no need to have them as participants here since I did the writing. And for the others, if there is anything that has to be added by them, then by all means, include them too when closing the issue.
